[package]
name = "enum-iterator"
version = "0.1.0"
authors = ["Bruce A. MacNaughton <bmacnaughton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "0.10.5"
quote = "0.3.10"

[lib]
proc-macro = true
